export const milkVendors = [
  {
    vendor_id: 1,
    name: "PureFlow Springs",
    location: "1.8 km away",
    contact: "+1-123-456-7890",
    email: "pureflow@example.com",
    products_offered: [
      "Natural Spring Water",
      "Purified Water",
      "Sparkling Water",
    ],
    delivery_options: ["Home Delivery", "Pickup"],
    working_hours: {
      Monday: "8:00 AM - 6:00 PM",
      Tuesday: "8:00 AM - 6:00 PM",
      Wednesday: "8:00 AM - 6:00 PM",
      Thursday: "8:00 AM - 6:00 PM",
      Friday: "8:00 AM - 6:00 PM",
      Saturday: "9:00 AM - 4:00 PM",
      Sunday: "Closed",
    },
    price: 0.01,
    rating: 4.5,
    website: "https://www.pureflowsprings.com",
  },
  {
    vendor_id: 2,
    name: "AquaPure Oasis",
    location: "800 m away",
    contact: "+1-987-654-3210",
    email: "aquapure@example.com",
    products_offered: ["Mineral Water", "Distilled Water", "Alkaline Water"],
    delivery_options: ["Home Delivery"],
    working_hours: {
      Monday: "9:00 AM - 5:00 PM",
      Tuesday: "9:00 AM - 5:00 PM",
      Wednesday: "9:00 AM - 5:00 PM",
      Thursday: "9:00 AM - 5:00 PM",
      Friday: "9:00 AM - 5:00 PM",
      Saturday: "10:00 AM - 2:00 PM",
      Sunday: "Closed",
    },
    price: 0.01,
    rating: 4.2,
    website: "https://www.aquapureoasis.com",
  },
  {
    vendor_id: 3,
    name: "CrystalClear Waters",
    location: "1.5 km away",
    contact: "+1-333-555-7777",
    email: "crystalclear@example.com",
    products_offered: [
      "Spring Water",
      "Fruit-Infused Water",
      "Electrolyte Water",
    ],
    delivery_options: ["Home Delivery", "Pickup"],
    working_hours: {
      Monday: "7:00 AM - 7:00 PM",
      Tuesday: "7:00 AM - 7:00 PM",
      Wednesday: "7:00 AM - 7:00 PM",
      Thursday: "7:00 AM - 7:00 PM",
      Friday: "7:00 AM - 7:00 PM",
      Saturday: "8:00 AM - 5:00 PM",
      Sunday: "Closed",
    },
    price: 0.01,
    rating: 4.7,
    website: "https://www.crystalclearwaters.com",
  },
  // Add more vendors as needed
];
