export const milkVendors = [
  {
    vendor_id: 1,
    name: "Fresh Dairy Delights",
    location: "123 Main Street, Cityville",
    price: 2.59,
    contact: "+1-123-456-7890",
    email: "freshdairy@example.com",
    products_offered: ["Whole Milk", "Skimmed Milk", "Organic Milk"],
    delivery_options: ["Home Delivery", "Pickup"],
    working_hours: {
      Monday: "8:00 AM - 6:00 PM",
      Tuesday: "8:00 AM - 6:00 PM",
      Wednesday: "8:00 AM - 6:00 PM",
      Thursday: "8:00 AM - 6:00 PM",
      Friday: "8:00 AM - 6:00 PM",
      Saturday: "9:00 AM - 4:00 PM",
      Sunday: "Closed",
    },
    rating: 4.5,
    website: "https://www.freshdairydelights.com",
  },
  {
    vendor_id: 2,
    name: "Happy Cow Farms",
    location: "456 Oak Avenue, Townsville",
    price: 3.99,
    contact: "+1-987-654-3210",
    email: "happycow@example.com",
    products_offered: ["Farm Fresh Milk", "Low-Fat Milk", "Flavored Milk"],
    delivery_options: ["Home Delivery"],
    working_hours: {
      Monday: "9:00 AM - 5:00 PM",
      Tuesday: "9:00 AM - 5:00 PM",
      Wednesday: "9:00 AM - 5:00 PM",
      Thursday: "9:00 AM - 5:00 PM",
      Friday: "9:00 AM - 5:00 PM",
      Saturday: "10:00 AM - 2:00 PM",
      Sunday: "Closed",
    },
    rating: 4.2,
    website: "https://www.happycowfarms.com",
  },
  {
    vendor_id: 3,
    name: "Organic Meadows",
    location: "789 Elm Street, Villageton",
    contact: "+1-333-555-7777",
    email: "organicmeadows@example.com",
    products_offered: ["Organic Cow Milk", "Almond Milk", "Soy Milk"],
    delivery_options: ["Home Delivery", "Pickup"],
    working_hours: {
      Monday: "7:00 AM - 7:00 PM",
      Tuesday: "7:00 AM - 7:00 PM",
      Wednesday: "7:00 AM - 7:00 PM",
      Thursday: "7:00 AM - 7:00 PM",
      Friday: "7:00 AM - 7:00 PM",
      Saturday: "8:00 AM - 5:00 PM",
      Sunday: "Closed",
    },
    price: 5.3,
    rating: 4.7,
    website: "https://www.organicmeadows.com",
  },
  {
    vendor_id: 4,
    name: "Healthy Harvest Dairy",
    location: "321 Pine Street, Farmington",
    contact: "+1-555-777-9999",
    email: "healthyharvest@example.com",
    products_offered: ["Fresh Cow Milk", "Goat Milk", "Lactose-Free Milk"],
    delivery_options: ["Home Delivery", "Pickup"],
    working_hours: {
      Monday: "8:30 AM - 5:00 PM",
      Tuesday: "8:30 AM - 5:00 PM",
      Wednesday: "8:30 AM - 5:00 PM",
      Thursday: "8:30 AM - 5:00 PM",
      Friday: "8:30 AM - 5:00 PM",
      Saturday: "9:00 AM - 1:00 PM",
      Sunday: "Closed",
    },
    price: 1.49,
    rating: 4.4,
    website: "https://www.healthyharvestdairy.com",
  },
  {
    vendor_id: 5,
    name: "Natural Bliss Farms",
    location: "567 Maple Avenue, Greenfield",
    contact: "+1-888-222-3333",
    email: "naturalbliss@example.com",
    products_offered: ["Raw Milk", "Grass-Fed Milk", "Homogenized Milk"],
    delivery_options: ["Home Delivery"],
    working_hours: {
      Monday: "10:00 AM - 6:00 PM",
      Tuesday: "10:00 AM - 6:00 PM",
      Wednesday: "10:00 AM - 6:00 PM",
      Thursday: "10:00 AM - 6:00 PM",
      Friday: "10:00 AM - 6:00 PM",
      Saturday: "Closed",
      Sunday: "Closed",
    },
    price: 2.99,
    rating: 4.6,
    website: "https://www.naturalblissfarms.com",
  },
  // Add more vendors as needed
];
